config/routes.rb
Rails.application.routes.draw do
  root "articles#index"
  
  devise_for :users, path: 'auth', path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    password: 'secret',
    confirmation: 'verification',
    unlock: 'unblock',
    registration: 'register',
    sign_up: 'cmon_let_me_in'
  }
  
  resources :articles, only: [:index]
  resources :searches, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  validates :title, presence: true, length: { minimum: 3 }
end

app/models/search.rb
class Search < ApplicationRecord
  validates :query, presence: true, length: { maximum: 255 }

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { minimum: 3 }
  validates :image, presence: true
  validates :email, presence: true, uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :articles, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  layout :set_layout

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name image])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[name image])
  end

  def set_layout
    if current_user
      'application'
    else
      'auth'
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  include SearchesHelper

  # GET /articles or /articles.json
  def index
    if params[:query].present?
      @articles = Article.where('lower(title) Like ?', "%#{params[:query].downcase}%").paginate(per_page: 10,
                                                                                                page: params[:page])
      create_search(params[:query], current_user.id)
    else
      @articles = Article.paginate(per_page: 10, page: params[:page])
    end
  end


  private

  def create_search(query, user_id)
    return unless query.present? && query.length >= 3

    new_query = Search.where(user_id:, confirmed: false).last

    if new_query && params[:confirmed].present?
      new_query.update(confirmed: true)
    elsif new_query && same_input?(query, new_query.query)
      new_query.update(query:)
    else
      Search.create(query:, user_id:)
    end
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def index
    @search_results = Search.where(user: current_user).group(:query).order(count: :desc).count
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
  def same_input?(string_a, string_b, threshold = 0.863)
    JaroWinkler.distance(string_a, string_b, ignore_case: true) >= threshold
  end
end

app/views/articles/_article.html.erb
<div id="<%= dom_id article %>">
  <li class="text-lg leading-loose py-8">
    <span class="hover:text-orange-700">
      <%= article.title %>
    </span>
  </li>
  <hr>
</div>

app/views/articles/_articles.html.erb
<%= turbo_frame_tag "articles" do %>
  <%= render articles %>
  <%= render "shared/pagination", collection: articles %>
<% end %>

app/views/articles/index.html.erb
<div class="my-6">
  <%= render "articles", articles: @articles %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <title>LiveSearch</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "flash", media: 'all',"data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "pagination", media: 'all',"data-turbo-track": "reload" %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.5/flowbite.turbo.min.js"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-16 ">
      <%= render "shared/navbar" %>
      <%= render "shared/flash" %>
      <div class="my-4">
        <%= yield %>
      </div>
    </main>
  </body>

</html>

app/views/layouts/auth.html.erb
<!DOCTYPE html>
<html>

  <head>
    <title>Auth Page</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "flash", media: 'all',"data-turbo-track": "reload" %>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.5/flowbite.turbo.min.js"></script>

    <%= javascript_importmap_tags %>
  </head>

  <body class="font-nunito text-base text-black dark:text-white dark:bg-slate-900">
    <section class="auth_container">
  
      <div class=" p-6 lg:ml-16">
        <div class="container max-w-[1000px]">
          <div class="flash"><%= render 'shared/flash' %> </div>
  
          <div class="grid md:grid-cols-2 grid-cols-1 items-center gap-[30px]">
            <div class="relative">
              <h3 class="mb-4 md:text-3xl md:leading-normal text-2xl leading-normal font-semibold text-center">Welcome<span class="text-indigo-600">
                  <% if request.path == '/auth/login' %>
                  Kindly Sign in
                  <% else %>
                  Kindly Sign up
                  <% end %>
                </span>
                
            </div>
  
            <div class="p-4 bg-white dark:bg-slate-900 shadow dark:shadow-gray-800">
              <%= yield %>
            </div>
          </div>
        </div>
      </div>
    </section>
  
  
  </body>

</html>

app/views/searches/index.html.erb
<h1 class="text-center font-bold text-2xl p-8">
  My searches( <%= pluralize(@search_results.length, 'Search') %>)
</h1>
<div class="flex  justify-center">


  <div
    class="w-full  max-w-md p-4 bg-white border border-gray-200 rounded-lg shadow sm:p-8 dark:bg-gray-800 dark:border-gray-700">

    <div class="flex items-center justify-between mb-4">
      <h5 class="text-xl font-bold leading-none text-gray-900 dark:text-white">Search term</h5>
      <span class="text-sm font-medium text-blue-600 hover:underline dark:text-blue-500">
        Number of occurrence:
      </span>
    </div>
    <div class="flow-root">
      <ul role="list" class="divide-y divide-gray-200 dark:divide-gray-700">
        <% if @search_results.empty? %>
        <p class="text-center text-gray-500 py-8">
          No results found
        </p>
        <% else %>
        <% @search_results.entries.each do |title, count| %>
        <li class="py-3 sm:py-4">
          <div class="flex items-center space-x-4">

            <div class="flex-1 min-w-0">

              <p class="text-sm text-gray-500 truncate dark:text-gray-400">
                <%= title%>
              </p>
            </div>
            <div class="inline-flex items-center text-base font-semibold text-gray-900 dark:text-white">
              <%= count %>
            </div>
          </div>
        </li>
        <% end %>
        <% end %>

      </ul>
    </div>
  </div>
</div>

app/views/shared/_flash.html.erb
<div class="flash__message">
  <% if flash[:error] %>
  <div class="alert alert-danger">
    <%= flash[:error] %>
  </div>
  <% end %>

  <% if flash[:alert] %>
  <div class="alert alert-warning">
    <%= flash[:alert] %>
  </div>
  <% end %>

  <% if flash[:notice] %>
  <div class="alert alert-success">
    <%= flash[:notice] %>
  </div>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<nav class="border-gray-200 bg-gray-50 dark:bg-gray-800 dark:border-gray-700">
  <div class="flex flex-wrap items-center justify-between mx-auto p-4">
      <%= link_to root_path, class:"flex items-center" do %>
      <img src="https://robohash.org/sitsequiquia.png?size=300x300&set=set4" class="h-8 mr-3" alt="Wise Quotes" />
      <span class="self-center text-2xl font-semibold whitespace-nowrap dark:text-white">Wise Quotes</span>
      <% end %>
    <button data-collapse-toggle="navbar-solid-bg" type="button"
      class="inline-flex items-center p-2 ml-3 text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600"
      aria-controls="navbar-solid-bg" aria-expanded="false">
      <span class="sr-only">Open main menu</span>
      <svg class="w-6 h-6" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20"
        xmlns="http://www.w3.org/2000/svg">
        <path fill-rule="evenodd"
          d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z"
          clip-rule="evenodd"></path>
      </svg>
    </button>
    <div class="hidden w-full md:block md:w-auto" id="navbar-solid-bg">
      <ul
        class="flex flex-col font-medium mt-4 rounded-lg bg-gray-50 md:flex-row md:space-x-8 md:mt-0 md:border-0 md:bg-transparent dark:bg-gray-800 md:dark:bg-transparent dark:border-gray-700">
        <li class="flex items-center">
          <%= link_to "Home", root_path, class: "block py-2 pl-3 pr-4 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 md:dark:hover:text-blue-500 dark:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700" %>
        </li>
        <li class="flex items-center">
          <%= link_to "My Searches", searches_path, class: "self-center block py-2 pl-3 pr-4 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent" %>
        </li>
        <li class="flex items-center">
          <%= render "shared/search" %>
        </li>
        <li class="flex items-center">

          <% if current_user %>
          <%= button_to "Logout", destroy_user_session_path, method: :delete, class: "block items-center px-4 py-2 border border-transparent text-base font-medium rounded-md text-white bg-red-600 hover:bg-red-700" %>
          <% else %>
          <%= link_to "Login", new_user_session_path, class: "block py-2 pl-3 pr-4 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 md:dark:hover:text-blue-500 dark:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700" %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_pagination.html.erb
<div class="text-center my-4">
  <div role="navigation" aria-label="Pagination" class="px-3 py-2 mx-2 text-gray-700 no-underline bg-white rounded-lg">
    <div class="flickr_pagination">
      <div class="my-4">
        <%= page_entries_info collection %>
      </div>
      <%= will_paginate collection %>
    </div>
  </div>
</div>

app/views/shared/_search.html.erb
<%= form_with(url: articles_path, method: :get, data: {controller: "search-form", turbo_frame: "articles", turbo_action: "advance"}) do |form| %>
  <div class="flex space-x-3">
    <%= form.text_field :query, class: " px-4 rounded border ring-0 focus:ring-4 focus:ring-orange-100 focus:shadow-none focus:border-orange-500 focus:outline-none", data: {action: "input->search-form#search"}, placeholder:"Search here ..." %>

  </div>
<% end %>